package xyz.tcreopargh.textconverter;

import android.annotation.SuppressLint;
import android.content.res.Configuration;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.MenuItem;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import androidx.appcompat.app.AppCompatActivity;
import java.util.Locale;
import java.util.Objects;

public class ViewHelpActivity extends AppCompatActivity {

    public static final String helpHtml =
            "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                    + "<!-- saved from url=(0058)http://tool.oschina.net/uploads/apidocs/jquery/regexp.html -->\n"
                    + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                    + "    \n"
                    + "    <head>\n"
                    + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                    + "        <title>正则表达式帮助</title>\n"
                    + "        <style type=\"text/css\">html, body { font-family: sans-serif; font-size: 1em; } table.wikitable { background: none repeat scroll 0 0 #F9F9F9; border: 1px solid #AAAAAA; border-collapse: collapse; color: black; } .wikitable th, .wikitable td { border: 1px solid #AAAAAA; padding: 0.2em; } .wikitable th { background: none repeat scroll 0 0 #F2F2F2; text-align: center; } p { line-height: 1.5em; margin: 0.4em 0 0.5em; } h2{ margin:0; font-weight:normal;}</style></head>\n"
                    + "    \n"
                    + "    <body>\n"
                    + "<h2>什么是正则表达式？</h2>\n"
                    + "\n"
                    + "<blockquote><p>正则表达式使用单个字符串来描述、匹配一系列匹配某个句法规则的字符串。\n"
                    + "在很多文本编辑器里，正则表达式通常被用来检索、替换那些匹配某个模式的文本。<br>\n"
                    + " ——维基百科</p></blockquote>\n"
                    + "\n"
                    + "<p>换句话说，就是一种字符串的匹配规则，使用正则表达式能够匹配到所有符合规则的字符串，如\"[a-z]\"能匹配所有小写英文字母，\"\\d+\"能匹配所有单个数字等。使用正则表达式，能够在处理大量文本时省时省力。</p>\n"
                    + "\n"
                    + "<h2>我该如何使用正则表达式？</h2>\n"
                    + "\n"
                    + "<p>本App提供了一些比较常用的正则表达式，您可以点击主界面右上角菜单中的“载入正则表达式”使用这些预设值。当然，您也可以根据下方提供的规则，自己编写正则表达式，并且可以将其存入正则表达式列表中，方便以后随时使用。</p>"
                    + "        <h2>表达式全集</h2>\n"
                    + "        <table class=\"wikitable\">\n"
                    + "            <tbody>\n"
                    + "                <tr>\n"
                    + "                    <th width=\"10%\">字符</th>\n"
                    + "                    <th width=\"90%\">描述</th></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\</th>\n"
                    + "                    <td>将下一个字符标记为一个特殊字符、或一个原义字符、或一个向后引用、或一个八进制转义符。例如，“\n"
                    + "                        <code>n</code>”匹配字符“\n"
                    + "                        <code>n</code>”。“\n"
                    + "                        <code>\\n</code>”匹配一个换行符。串行“\n"
                    + "                        <code>\\\\</code>”匹配“\n"
                    + "                        <code>\\</code>”而“\n"
                    + "                        <code>\\(</code>”则匹配“\n"
                    + "                        <code>(</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">^</th>\n"
                    + "                    <td>匹配输入字符串的开始位置。如果设置了RegExp对象的Multiline属性，^也匹配“\n"
                    + "                        <code>\\n</code>”或“\n"
                    + "                        <code>\\r</code>”之后的位置。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">$</th>\n"
                    + "                    <td>匹配输入字符串的结束位置。如果设置了RegExp对象的Multiline属性，$也匹配“\n"
                    + "                        <code>\\n</code>”或“\n"
                    + "                        <code>\\r</code>”之前的位置。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">*</th>\n"
                    + "                    <td>匹配前面的子表达式零次或多次。例如，zo*能匹配“\n"
                    + "                        <code>z</code>”以及“\n"
                    + "                        <code>zoo</code>”。*等价于{0,}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">+</th>\n"
                    + "                    <td>匹配前面的子表达式一次或多次。例如，“\n"
                    + "                        <code>zo+</code>”能匹配“\n"
                    + "                        <code>zo</code>”以及“\n"
                    + "                        <code>zoo</code>”，但不能匹配“\n"
                    + "                        <code>z</code>”。+等价于{1,}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">?</th>\n"
                    + "                    <td>匹配前面的子表达式零次或一次。例如，“\n"
                    + "                        <code>do(es)?</code>”可以匹配“\n"
                    + "                        <code>does</code>”或“\n"
                    + "                        <code>does</code>”中的“\n"
                    + "                        <code>do</code>”。?等价于{0,1}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一个非负整数。匹配确定的\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次。例如，“\n"
                    + "                        <code>o{2}</code>”不能匹配“\n"
                    + "                        <code>Bob</code>”中的“\n"
                    + "                        <code>o</code>”，但是能匹配“\n"
                    + "                        <code>food</code>”中的两个o。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一个非负整数。至少匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次。例如，“\n"
                    + "                        <code>o{2,}</code>”不能匹配“\n"
                    + "                        <code>Bob</code>”中的“\n"
                    + "                        <code>o</code>”，但能匹配“\n"
                    + "                        <code>foooood</code>”中的所有o。“\n"
                    + "                        <code>o{1,}</code>”等价于“\n"
                    + "                        <code>o+</code>”。“\n"
                    + "                        <code>o{0,}</code>”则等价于“\n"
                    + "                        <code>o*</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>和\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>均为非负整数，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>&lt;=\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>。最少匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次且最多匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>次。例如，“\n"
                    + "                        <code>o{1,3}</code>”将匹配“\n"
                    + "                        <code>fooooood</code>”中的前三个o。“\n"
                    + "                        <code>o{0,1}</code>”等价于“\n"
                    + "                        <code>o?</code>”。请注意在逗号和两个数之间不能有空格。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">?</th>\n"
                    + "                    <td>当该字符紧跟在任何一个其他限制符（*,+,?，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>}，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,}，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>}）后面时，匹配模式是非贪婪的。非贪婪模式尽可能少的匹配所搜索的字符串，而默认的贪婪模式则尽可能多的匹配所搜索的字符串。例如，对于字符串“\n"
                    + "                        <code>oooo</code>”，“\n"
                    + "                        <code>o+?</code>”将匹配单个“\n"
                    + "                        <code>o</code>”，而“\n"
                    + "                        <code>o+</code>”将匹配所有“\n"
                    + "                        <code>o</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">.</th>\n"
                    + "                    <td>匹配除“\n"
                    + "                        <code>\\</code>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">\n"
                    + "                            <code>n</code></span>”之外的任何单个字符。要匹配包括“\n"
                    + "                        <code>\\</code>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">\n"
                    + "                            <code>n</code></span>”在内的任何字符，请使用像“\n"
                    + "                        <code>(.|\\n)</code>”的模式。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(pattern)</th>\n"
                    + "                    <td>匹配pattern并获取这一匹配。所获取的匹配可以从产生的Matches集合得到，在VBScript中使用SubMatches集合，在JScript中则使用$0…$9属性。要匹配圆括号字符，请使用“\n"
                    + "                        <code>\\(</code>”或“\n"
                    + "                        <code>\\)</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?:pattern)</th>\n"
                    + "                    <td>匹配pattern但不获取匹配结果，也就是说这是一个非获取匹配，不进行存储供以后使用。这在使用或字符“\n"
                    + "                        <code>(|)</code>”来组合一个模式的各个部分是很有用。例如“\n"
                    + "                        <code>industr(?:y|ies)</code>”就是一个比“\n"
                    + "                        <code>industry|industries</code>”更简略的表达式。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?=pattern)</th>\n"
                    + "                    <td>正向肯定预查，在任何匹配pattern的字符串开始处匹配查找字符串。这是一个非获取匹配，也就是说，该匹配不需要获取供以后使用。例如，“\n"
                    + "                        <code>Windows(?=95|98|NT|2000)</code>”能匹配“\n"
                    + "                        <code>Windows2000</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>Windows3.1</code>”中的“\n"
                    + "                        <code>Windows</code>”。预查不消耗字符，也就是说，在一个匹配发生后，在最后一次匹配之后立即开始下一次匹配的搜索，而不是从包含预查的字符之后开始。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?!pattern)</th>\n"
                    + "                    <td>正向否定预查，在任何不匹配pattern的字符串开始处匹配查找字符串。这是一个非获取匹配，也就是说，该匹配不需要获取供以后使用。例如“\n"
                    + "                        <code>Windows(?!95|98|NT|2000)</code>”能匹配“\n"
                    + "                        <code>Windows3.1</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>Windows2000</code>”中的“\n"
                    + "                        <code>Windows</code>”。预查不消耗字符，也就是说，在一个匹配发生后，在最后一次匹配之后立即开始下一次匹配的搜索，而不是从包含预查的字符之后开始</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?&lt;=pattern)</th>\n"
                    + "                    <td>反向肯定预查，与正向肯定预查类拟，只是方向相反。例如，“\n"
                    + "                        <code>(?&lt;=95|98|NT|2000)Windows</code>”能匹配“\n"
                    + "                        <code>2000Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>3.1Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?&lt;!pattern)</th>\n"
                    + "                    <td>反向否定预查，与正向否定预查类拟，只是方向相反。例如“\n"
                    + "                        <code>(?&lt;!95|98|NT|2000)Windows</code>”能匹配“\n"
                    + "                        <code>3.1Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>2000Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">x|y</th>\n"
                    + "                    <td>匹配x或y。例如，“\n"
                    + "                        <code>z|food</code>”能匹配“\n"
                    + "                        <code>z</code>”或“\n"
                    + "                        <code>food</code>”。“\n"
                    + "                        <code>(z|f)ood</code>”则匹配“\n"
                    + "                        <code>zood</code>”或“\n"
                    + "                        <code>food</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[xyz]</th>\n"
                    + "                    <td>字符集合。匹配所包含的任意一个字符。例如，“\n"
                    + "                        <code>[abc]</code>”可以匹配“\n"
                    + "                        <code>plain</code>”中的“\n"
                    + "                        <code>a</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[^xyz]</th>\n"
                    + "                    <td>负值字符集合。匹配未包含的任意字符。例如，“\n"
                    + "                        <code>[^abc]</code>”可以匹配“\n"
                    + "                        <code>plain</code>”中的“\n"
                    + "                        <code>p</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[a-z]</th>\n"
                    + "                    <td>字符范围。匹配指定范围内的任意字符。例如，“\n"
                    + "                        <code>[a-z]</code>”可以匹配“\n"
                    + "                        <code>a</code>”到“\n"
                    + "                        <code>z</code>”范围内的任意小写字母字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[^a-z]</th>\n"
                    + "                    <td>负值字符范围。匹配任何不在指定范围内的任意字符。例如，“\n"
                    + "                        <code>[^a-z]</code>”可以匹配任何不在“\n"
                    + "                        <code>a</code>”到“\n"
                    + "                        <code>z</code>”范围内的任意字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\b</th>\n"
                    + "                    <td>匹配一个单词边界，也就是指单词和空格间的位置。例如，“\n"
                    + "                        <code>er\\b</code>”可以匹配“\n"
                    + "                        <code>never</code>”中的“\n"
                    + "                        <code>er</code>”，但不能匹配“\n"
                    + "                        <code>verb</code>”中的“\n"
                    + "                        <code>er</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\B</th>\n"
                    + "                    <td>匹配非单词边界。“\n"
                    + "                        <code>er\\B</code>”能匹配“\n"
                    + "                        <code>verb</code>”中的“\n"
                    + "                        <code>er</code>”，但不能匹配“\n"
                    + "                        <code>never</code>”中的“\n"
                    + "                        <code>er</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\cx</th>\n"
                    + "                    <td>匹配由x指明的控制字符。例如，\\cM匹配一个Control-M或回车符。x的值必须为A-Z或a-z之一。否则，将c视为一个原义的“\n"
                    + "                        <code>c</code>”字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\d</th>\n"
                    + "                    <td>匹配一个数字字符。等价于[0-9]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\D</th>\n"
                    + "                    <td>匹配一个非数字字符。等价于[^0-9]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\f</th>\n"
                    + "                    <td>匹配一个换页符。等价于\\x0c和\\cL。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\n</th>\n"
                    + "                    <td>匹配一个换行符。等价于\\x0a和\\cJ。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\r</th>\n"
                    + "                    <td>匹配一个回车符。等价于\\x0d和\\cM。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\s</th>\n"
                    + "                    <td>匹配任何空白字符，包括空格、制表符、换页符等等。等价于[ \\f\\n\\r\\t\\v]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\S</th>\n"
                    + "                    <td>匹配任何非空白字符。等价于[^ \\f\\n\\r\\t\\v]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\t</th>\n"
                    + "                    <td>匹配一个制表符。等价于\\x09和\\cI。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\v</th>\n"
                    + "                    <td>匹配一个垂直制表符。等价于\\x0b和\\cK。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\w</th>\n"
                    + "                    <td>匹配包括下划线的任何单词字符。等价于“\n"
                    + "                        <code>[A-Za-z0-9_]</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\W</th>\n"
                    + "                    <td>匹配任何非单词字符。等价于“\n"
                    + "                        <code>[^A-Za-z0-9_]</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\x\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为十六进制转义值。十六进制转义值必须为确定的两个数字长。例如，“\n"
                    + "                        <code>\\x41</code>”匹配“\n"
                    + "                        <code>A</code>”。“\n"
                    + "                        <code>\\x041</code>”则等价于“\n"
                    + "                        <code>\\x04&amp;1</code>”。正则表达式中可以使用ASCII编码。.</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span>是一个正整数。对所获取的匹配的引用。例如，“\n"
                    + "                        <code>(.)\\1</code>”匹配两个连续的相同字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>标识一个八进制转义值或一个向后引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>之前至少\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>个获取的子表达式，则\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为向后引用。否则，如果\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为八进制数字（0-7），则\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为一个八进制转义值。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span></th>\n"
                    + "                    <td>标识一个八进制转义值或一个向后引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>之前至少有\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>个获得子表达式，则\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>为向后引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>之前至少有\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>个获取，则\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为一个后跟文字\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>的向后引用。如果前面的条件都不满足，若\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>和\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>均为八进制数字（0-7），则\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>将匹配八进制转义值\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nml</span></th>\n"
                    + "                    <td>如果\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>为八进制数字（0-3），且\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m和l</span>均为八进制数字（0-7），则匹配八进制转义值\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>l。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\u\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一个用四个十六进制数字表示的Unicode字符。例如，\\u00A9匹配版权符号（©）。</td></tr>\n"
                    + "            </tbody>\n"
                    + "        </table>\n"
                    + "        <br>\n"
                    + "        <h2>常用正则表达式</h2>\n"
                    + "        <table class=\"wikitable\" width=\"100%\">\n"
                    + "            <tbody>\n"
                    + "                <tr>\n"
                    + "                    <th width=\"10%\">用户名</th>\n"
                    + "                    <td width=\"90%\">/^[a-z0-9_-]{3,16}$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">密码</th>\n"
                    + "                    <td>/^[a-z0-9_-]{6,18}$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">十六进制值</th>\n"
                    + "                    <td>/^#?([a-f0-9]{6}|[a-f0-9]{3})$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">电子邮箱</th>\n"
                    + "                    <td>/^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/\n"
                    + "                        <br>/^[a-z\\d]+(\\.[a-z\\d]+)*@([\\da-z](-[\\da-z])?)+(\\.{1,2}[a-z]+)+$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">URL</th>\n"
                    + "                    <td>/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">IP 地址</th>\n"
                    + "                    <td>/((2[0-4]\\d|25[0-5]|[01]?\\d\\d?)\\.){3}(2[0-4]\\d|25[0-5]|[01]?\\d\\d?)/\n"
                    + "                        <br>/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">HTML 标签</th>\n"
                    + "                    <td>/^&lt;([a-z]+)([^&lt;]+)*(?:&gt;(.*)&lt;\\/\\1&gt;|\\s+\\/&gt;)$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">删除代码\\\\注释</th>\n"
                    + "                    <td>(?&lt;!http:|\\S)//.*$</td></tr>\n"
                    + "                <!-- <tr>\n"
                    + "                <th scope=\"row\">&nbsp;</th>\n"
                    + "                <td>&nbsp;</td></tr>-->\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">Unicode编码中的汉字范围</th>\n"
                    + "                    <td>/^[\\u2E80-\\u9FFF]+$/</td></tr>\n"
                    + "            </tbody>\n"
                    + "        </table>\n"
                    + "       <h4>以上表格来源：tool.oschina.net</h4>"
                    + "    </body>\n"
                    + "\n"
                    + "</html>";

    public static final String helpHtmlTraditional =
            "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                    + "<!-- saved from url=(0058)http://tool.oschina.net/uploads/apidocs/jquery/regexp.html -->\n"
                    + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                    + "    \n"
                    + "    <head>\n"
                    + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                    + "        <title>正則表達式幫助</title>\n"
                    + "        <style type=\"text/css\">html, body { font-family: sans-serif; font-size: 1em; } table.wikitable { background: none repeat scroll 0 0 #F9F9F9; border: 1px solid #AAAAAA; border-collapse: collapse; color: black; } .wikitable th, .wikitable td { border: 1px solid #AAAAAA; padding: 0.2em; } .wikitable th { background: none repeat scroll 0 0 #F2F2F2; text-align: center; } p { line-height: 1.5em; margin: 0.4em 0 0.5em; } h2{ margin:0; font-weight:normal;}</style></head>\n"
                    + "    \n"
                    + "    <body>\n"
                    + "<h2>什麽是正則表達式？</h2>\n"
                    + "\n"
                    + "<blockquote><p>正則表達式使用單個字符串來描述、匹配一系列匹配某個句法規則的字符串。\n"
                    + "在很多文本編輯器裏，正則表達式通常被用來檢索、替換那些匹配某個模式的文本。<br>\n"
                    + " ——維基百科</p></blockquote>\n"
                    + "\n"
                    + "<p>換句話說，就是一種字符串的匹配規則，使用正則表達式能夠匹配到所有符合規則的字符串，如\"[a-z]\"能匹配所有小寫英文字母，\"\\d+\"能匹配所有單個數字等。使用正則表達式，能夠在處理大量文本時省時省力。</p>\n"
                    + "\n"
                    + "<h2>我該如何使用正則表達式？</h2>\n"
                    + "\n"
                    + "<p>本App提供了一些比較常用的正則表達式，您可以點擊主界面右上角菜單中的“載入正則表達式”使用這些預設值。當然，您也可以根據下方提供的規則，自己編寫正則表達式，並且可以將其存入正則表達式列表中，方便以後隨時使用。</p>\n"
                    + "        <h2>表達式全集</h2>\n"
                    + "        <table class=\"wikitable\">\n"
                    + "            <tbody>\n"
                    + "                <tr>\n"
                    + "                    <th width=\"10%\">字符</th>\n"
                    + "                    <th width=\"90%\">描述</th></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\</th>\n"
                    + "                    <td>將下一個字符標記為一個特殊字符、或一個原義字符、或一個向後引用、或一個八進制轉義符。例如，“\n"
                    + "                        <code>n</code>”匹配字符“\n"
                    + "                        <code>n</code>”。“\n"
                    + "                        <code>\\n</code>”匹配一個換行符。串行“\n"
                    + "                        <code>\\\\</code>”匹配“\n"
                    + "                        <code>\\</code>”而“\n"
                    + "                        <code>\\(</code>”則匹配“\n"
                    + "                        <code>(</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">^</th>\n"
                    + "                    <td>匹配輸入字符串的開始位置。如果設置了RegExp對象的Multiline屬性，^也匹配“\n"
                    + "                        <code>\\n</code>”或“\n"
                    + "                        <code>\\r</code>”之後的位置。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">$</th>\n"
                    + "                    <td>匹配輸入字符串的結束位置。如果設置了RegExp對象的Multiline屬性，$也匹配“\n"
                    + "                        <code>\\n</code>”或“\n"
                    + "                        <code>\\r</code>”之前的位置。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">*</th>\n"
                    + "                    <td>匹配前面的子表達式零次或多次。例如，zo*能匹配“\n"
                    + "                        <code>z</code>”以及“\n"
                    + "                        <code>zoo</code>”。*等價於{0,}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">+</th>\n"
                    + "                    <td>匹配前面的子表達式一次或多次。例如，“\n"
                    + "                        <code>zo+</code>”能匹配“\n"
                    + "                        <code>zo</code>”以及“\n"
                    + "                        <code>zoo</code>”，但不能匹配“\n"
                    + "                        <code>z</code>”。+等價於{1,}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">?</th>\n"
                    + "                    <td>匹配前面的子表達式零次或一次。例如，“\n"
                    + "                        <code>do(es)?</code>”可以匹配“\n"
                    + "                        <code>does</code>”或“\n"
                    + "                        <code>does</code>”中的“\n"
                    + "                        <code>do</code>”。?等價於{0,1}。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一個非負整數。匹配確定的\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次。例如，“\n"
                    + "                        <code>o{2}</code>”不能匹配“\n"
                    + "                        <code>Bob</code>”中的“\n"
                    + "                        <code>o</code>”，但是能匹配“\n"
                    + "                        <code>food</code>”中的兩個o。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一個非負整數。至少匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次。例如，“\n"
                    + "                        <code>o{2,}</code>”不能匹配“\n"
                    + "                        <code>Bob</code>”中的“\n"
                    + "                        <code>o</code>”，但能匹配“\n"
                    + "                        <code>foooood</code>”中的所有o。“\n"
                    + "                        <code>o{1,}</code>”等價於“\n"
                    + "                        <code>o+</code>”。“\n"
                    + "                        <code>o{0,}</code>”則等價於“\n"
                    + "                        <code>o*</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>}</th>\n"
                    + "                    <td>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>和\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>均為非負整數，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>&lt;=\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>。最少匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>次且最多匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>次。例如，“\n"
                    + "                        <code>o{1,3}</code>”將匹配“\n"
                    + "                        <code>fooooood</code>”中的前三個o。“\n"
                    + "                        <code>o{0,1}</code>”等價於“\n"
                    + "                        <code>o?</code>”。請註意在逗號和兩個數之間不能有空格。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">?</th>\n"
                    + "                    <td>當該字符緊跟在任何一個其他限制符（*,+,?，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>}，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,}，{\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>,\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>}）後面時，匹配模式是非貪婪的。非貪婪模式盡可能少的匹配所搜索的字符串，而默認的貪婪模式則盡可能多的匹配所搜索的字符串。例如，對於字符串“\n"
                    + "                        <code>oooo</code>”，“\n"
                    + "                        <code>o+?</code>”將匹配單個“\n"
                    + "                        <code>o</code>”，而“\n"
                    + "                        <code>o+</code>”將匹配所有“\n"
                    + "                        <code>o</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">.</th>\n"
                    + "                    <td>匹配除“\n"
                    + "                        <code>\\</code>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">\n"
                    + "                            <code>n</code></span>”之外的任何單個字符。要匹配包括“\n"
                    + "                        <code>\\</code>\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">\n"
                    + "                            <code>n</code></span>”在內的任何字符，請使用像“\n"
                    + "                        <code>(.|\\n)</code>”的模式。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(pattern)</th>\n"
                    + "                    <td>匹配pattern並獲取這一匹配。所獲取的匹配可以從產生的Matches集合得到，在VBScript中使用SubMatches集合，在JScript中則使用$0…$9屬性。要匹配圓括號字符，請使用“\n"
                    + "                        <code>\\(</code>”或“\n"
                    + "                        <code>\\)</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?:pattern)</th>\n"
                    + "                    <td>匹配pattern但不獲取匹配結果，也就是說這是一個非獲取匹配，不進行存儲供以後使用。這在使用或字符“\n"
                    + "                        <code>(|)</code>”來組合一個模式的各個部分是很有用。例如“\n"
                    + "                        <code>industr(?:y|ies)</code>”就是一個比“\n"
                    + "                        <code>industry|industries</code>”更簡略的表達式。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?=pattern)</th>\n"
                    + "                    <td>正向肯定預查，在任何匹配pattern的字符串開始處匹配查找字符串。這是一個非獲取匹配，也就是說，該匹配不需要獲取供以後使用。例如，“\n"
                    + "                        <code>Windows(?=95|98|NT|2000)</code>”能匹配“\n"
                    + "                        <code>Windows2000</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>Windows3.1</code>”中的“\n"
                    + "                        <code>Windows</code>”。預查不消耗字符，也就是說，在一個匹配發生後，在最後一次匹配之後立即開始下一次匹配的搜索，而不是從包含預查的字符之後開始。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?!pattern)</th>\n"
                    + "                    <td>正向否定預查，在任何不匹配pattern的字符串開始處匹配查找字符串。這是一個非獲取匹配，也就是說，該匹配不需要獲取供以後使用。例如“\n"
                    + "                        <code>Windows(?!95|98|NT|2000)</code>”能匹配“\n"
                    + "                        <code>Windows3.1</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>Windows2000</code>”中的“\n"
                    + "                        <code>Windows</code>”。預查不消耗字符，也就是說，在一個匹配發生後，在最後一次匹配之後立即開始下一次匹配的搜索，而不是從包含預查的字符之後開始</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?&lt;=pattern)</th>\n"
                    + "                    <td>反向肯定預查，與正向肯定預查類擬，只是方向相反。例如，“\n"
                    + "                        <code>(?&lt;=95|98|NT|2000)Windows</code>”能匹配“\n"
                    + "                        <code>2000Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>3.1Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">(?&lt;!pattern)</th>\n"
                    + "                    <td>反向否定預查，與正向否定預查類擬，只是方向相反。例如“\n"
                    + "                        <code>(?&lt;!95|98|NT|2000)Windows</code>”能匹配“\n"
                    + "                        <code>3.1Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”，但不能匹配“\n"
                    + "                        <code>2000Windows</code>”中的“\n"
                    + "                        <code>Windows</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">x|y</th>\n"
                    + "                    <td>匹配x或y。例如，“\n"
                    + "                        <code>z|food</code>”能匹配“\n"
                    + "                        <code>z</code>”或“\n"
                    + "                        <code>food</code>”。“\n"
                    + "                        <code>(z|f)ood</code>”則匹配“\n"
                    + "                        <code>zood</code>”或“\n"
                    + "                        <code>food</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[xyz]</th>\n"
                    + "                    <td>字符集合。匹配所包含的任意一個字符。例如，“\n"
                    + "                        <code>[abc]</code>”可以匹配“\n"
                    + "                        <code>plain</code>”中的“\n"
                    + "                        <code>a</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[^xyz]</th>\n"
                    + "                    <td>負值字符集合。匹配未包含的任意字符。例如，“\n"
                    + "                        <code>[^abc]</code>”可以匹配“\n"
                    + "                        <code>plain</code>”中的“\n"
                    + "                        <code>p</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[a-z]</th>\n"
                    + "                    <td>字符範圍。匹配指定範圍內的任意字符。例如，“\n"
                    + "                        <code>[a-z]</code>”可以匹配“\n"
                    + "                        <code>a</code>”到“\n"
                    + "                        <code>z</code>”範圍內的任意小寫字母字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">[^a-z]</th>\n"
                    + "                    <td>負值字符範圍。匹配任何不在指定範圍內的任意字符。例如，“\n"
                    + "                        <code>[^a-z]</code>”可以匹配任何不在“\n"
                    + "                        <code>a</code>”到“\n"
                    + "                        <code>z</code>”範圍內的任意字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\b</th>\n"
                    + "                    <td>匹配一個單詞邊界，也就是指單詞和空格間的位置。例如，“\n"
                    + "                        <code>er\\b</code>”可以匹配“\n"
                    + "                        <code>never</code>”中的“\n"
                    + "                        <code>er</code>”，但不能匹配“\n"
                    + "                        <code>verb</code>”中的“\n"
                    + "                        <code>er</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\B</th>\n"
                    + "                    <td>匹配非單詞邊界。“\n"
                    + "                        <code>er\\B</code>”能匹配“\n"
                    + "                        <code>verb</code>”中的“\n"
                    + "                        <code>er</code>”，但不能匹配“\n"
                    + "                        <code>never</code>”中的“\n"
                    + "                        <code>er</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\cx</th>\n"
                    + "                    <td>匹配由x指明的控制字符。例如，\\cM匹配一個Control-M或回車符。x的值必須為A-Z或a-z之一。否則，將c視為一個原義的“\n"
                    + "                        <code>c</code>”字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\d</th>\n"
                    + "                    <td>匹配一個數字字符。等價於[0-9]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\D</th>\n"
                    + "                    <td>匹配一個非數字字符。等價於[^0-9]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\f</th>\n"
                    + "                    <td>匹配一個換頁符。等價於\\x0c和\\cL。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\n</th>\n"
                    + "                    <td>匹配一個換行符。等價於\\x0a和\\cJ。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\r</th>\n"
                    + "                    <td>匹配一個回車符。等價於\\x0d和\\cM。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\s</th>\n"
                    + "                    <td>匹配任何空白字符，包括空格、制表符、換頁符等等。等價於[ \\f\\n\\r\\t\\v]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\S</th>\n"
                    + "                    <td>匹配任何非空白字符。等價於[^ \\f\\n\\r\\t\\v]。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\t</th>\n"
                    + "                    <td>匹配一個制表符。等價於\\x09和\\cI。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\v</th>\n"
                    + "                    <td>匹配一個垂直制表符。等價於\\x0b和\\cK。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\w</th>\n"
                    + "                    <td>匹配包括下劃線的任何單詞字符。等價於“\n"
                    + "                        <code>[A-Za-z0-9_]</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\W</th>\n"
                    + "                    <td>匹配任何非單詞字符。等價於“\n"
                    + "                        <code>[^A-Za-z0-9_]</code>”。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\x\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為十六進制轉義值。十六進制轉義值必須為確定的兩個數字長。例如，“\n"
                    + "                        <code>\\x41</code>”匹配“\n"
                    + "                        <code>A</code>”。“\n"
                    + "                        <code>\\x041</code>”則等價於“\n"
                    + "                        <code>\\x04&amp;1</code>”。正則表達式中可以使用ASCII編碼。.</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">num</span>是一個正整數。對所獲取的匹配的引用。例如，“\n"
                    + "                        <code>(.)\\1</code>”匹配兩個連續的相同字符。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>標識一個八進制轉義值或一個向後引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>之前至少\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>個獲取的子表達式，則\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為向後引用。否則，如果\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為八進制數字（0-7），則\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為一個八進制轉義值。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span></th>\n"
                    + "                    <td>標識一個八進制轉義值或一個向後引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>之前至少有\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>個獲得子表達式，則\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>為向後引用。如果\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>之前至少有\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>個獲取，則\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為一個後跟文字\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>的向後引用。如果前面的條件都不滿足，若\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>和\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m</span>均為八進制數字（0-7），則\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>將匹配八進制轉義值\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nml</span></th>\n"
                    + "                    <td>如果\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>為八進制數字（0-3），且\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">m和l</span>均為八進制數字（0-7），則匹配八進制轉義值\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">nm</span>l。</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th style=\"text-align:center;\">\\u\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span></th>\n"
                    + "                    <td>匹配\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>，其中\n"
                    + "                        <span style=\"font-family:Times New Roman; font-style:italic;\">n</span>是一個用四個十六進制數字表示的Unicode字符。例如，\\u00A9匹配版權符號（©）。</td></tr>\n"
                    + "            </tbody>\n"
                    + "        </table>\n"
                    + "        <br>\n"
                    + "        <h2>常用正則表達式</h2>\n"
                    + "        <table class=\"wikitable\" width=\"100%\">\n"
                    + "            <tbody>\n"
                    + "                <tr>\n"
                    + "                    <th width=\"10%\">用戶名</th>\n"
                    + "                    <td width=\"90%\">/^[a-z0-9_-]{3,16}$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">密碼</th>\n"
                    + "                    <td>/^[a-z0-9_-]{6,18}$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">十六進制值</th>\n"
                    + "                    <td>/^#?([a-f0-9]{6}|[a-f0-9]{3})$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">電子郵箱</th>\n"
                    + "                    <td>/^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/\n"
                    + "                        <br>/^[a-z\\d]+(\\.[a-z\\d]+)*@([\\da-z](-[\\da-z])?)+(\\.{1,2}[a-z]+)+$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">URL</th>\n"
                    + "                    <td>/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">IP 地址</th>\n"
                    + "                    <td>/((2[0-4]\\d|25[0-5]|[01]?\\d\\d?)\\.){3}(2[0-4]\\d|25[0-5]|[01]?\\d\\d?)/\n"
                    + "                        <br>/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">HTML 標簽</th>\n"
                    + "                    <td>/^&lt;([a-z]+)([^&lt;]+)*(?:&gt;(.*)&lt;\\/\\1&gt;|\\s+\\/&gt;)$/</td></tr>\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">刪除代碼\\\\註釋</th>\n"
                    + "                    <td>(?&lt;!http:|\\S)//.*$</td></tr>\n"
                    + "                <!-- <tr>\n"
                    + "                <th scope=\"row\">&nbsp;</th>\n"
                    + "                <td>&nbsp;</td></tr>-->\n"
                    + "                <tr>\n"
                    + "                    <th scope=\"row\">Unicode編碼中的漢字範圍</th>\n"
                    + "                    <td>/^[\\u2E80-\\u9FFF]+$/</td></tr>\n"
                    + "            </tbody>\n"
                    + "        </table>\n"
                    + "       <h4>以上表格來源：tool.oschina.net</h4>\n"
                    + "    </body>\n"
                    + "\n"
                    + "</html>";

    @SuppressLint("SetJavaScriptEnabled")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_help);
        Objects.requireNonNull(getSupportActionBar()).setDisplayHomeAsUpEnabled(true);
        WebView viewHelp = findViewById(R.id.viewHelpPage);
        viewHelp.setWebViewClient(new WebViewClient());
        /*viewHelp.getSettings().setJavaScriptEnabled(true);
        viewHelp.setWebViewClient(new WebViewClient(){
            @Override
            public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error){
                handler.proceed();
            }
        });*/
        Resources resources = getResources();
        Configuration config = resources.getConfiguration();
        String newValue =
                getSharedPreferences("settings", MODE_PRIVATE).getString("appLanguage", "auto");
        if (newValue != null) {
            switch (newValue) {
                case "auto":
                    config.setLocale(Locale.getDefault());
                    break;
                case "en-us":
                    config.setLocale(Locale.ENGLISH);
                    break;
                case "zh-cn":
                    config.setLocale(Locale.SIMPLIFIED_CHINESE);
                    break;
                case "zh-hk":
                    config.setLocale(Locale.TRADITIONAL_CHINESE);
                    break;
            }
        }
        if (config.locale == Locale.CHINA || config.locale == Locale.SIMPLIFIED_CHINESE) {
            viewHelp.loadDataWithBaseURL(null, helpHtml, "text/html", "UTF-8", null);
        } else if (config.locale == Locale.TAIWAN || config.locale == Locale.TRADITIONAL_CHINESE) {
            viewHelp.loadDataWithBaseURL(null, helpHtmlTraditional, "text/html", "UTF-8", null);
        } else {
            viewHelp.loadUrl("https://en.wikipedia.org/wiki/Regular_expression");
        }
    }

    public void returnHome() {
        finish();
    }

    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                returnHome();
                break;
        }
        return true;
    }
}
